### ISSUE TITLE
Time based playing

### ISSUE THREAD

**Issue by Suplanus** [Suplanus/Cuterdio#92]
# Description
- 09pm: Play Station RadioA
- 12pm: RadioB

# Milestones
- [x] Menu-Button
- [x] Page
- [x] Add
- [x] Edit
- [x] Player
- [x] Text-to-speach
- [x] Notification
- [x] Timeline view
- [x] In-App-Purchase
- [x] Set current station correct
- [x] Screenshot
- [x] Cover image on station change
- [x] [Bug-Fix TimePicker](https://github.com/xamarin/Xamarin.Forms/issues/11963)
